// Package skilldoc generates the reference documents of the figctl agent
// skill from the command tree and the JSON Schema registry, so the
// installed skill always describes the binary that installed it.
//
// cmd/gen-skill-docs writes the output into internal/skill/templates,
// where it is embedded; a test in this package fails when the committed
// files no longer match.
package skilldoc

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/tiaanduplessis/figctl/internal/cli"
)

// Documents are the generated files, keyed by their path inside
// internal/skill/templates.
const (
	CommandsPath = "reference/commands.md"
	SchemasPath  = "reference/output-schemas.md"
)

// generatedNotice heads every generated file.
const generatedNotice = "Generated by `make gen` from the figctl command tree. Do not edit."

// Documents returns the generated documents keyed by path.
func Documents() map[string]string {
	return map[string]string{
		CommandsPath: Commands(),
		SchemasPath:  OutputSchemas(),
	}
}

// Commands renders the command reference: every command with its flags
// and one example, taken from the same cobra definitions as --help.
func Commands() string {
	var b strings.Builder
	b.WriteString("# figctl command reference\n\n")
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("`<ref>` is a file key or any Figma URL. When the URL carries `node-id=1-2`\n")
	b.WriteString("figctl converts it to `1:2` and uses it as the default `--node`, so paste the\n")
	b.WriteString("URL as given.\n\n")

	root := cli.Root()
	b.WriteString("## Global flags\n\n")
	b.WriteString("Every command accepts these.\n\n")
	writeFlagTable(&b, root.PersistentFlags())
	b.WriteString("\n")

	b.WriteString("## Commands\n\n")
	for _, cmd := range walk(root) {
		writeCommand(&b, cmd)
	}
	return b.String()
}

// walk returns the runnable commands of the tree in path order, skipping
// hidden commands and cobra's own help command.
func walk(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var visit func(*cobra.Command)
	visit = func(cmd *cobra.Command) {
		for _, sub := range cmd.Commands() {
			if sub.Hidden || sub.Name() == "help" {
				continue
			}
			if sub.Runnable() {
				out = append(out, sub)
			}
			visit(sub)
		}
	}
	visit(root)
	sort.SliceStable(out, func(i, j int) bool { return out[i].CommandPath() < out[j].CommandPath() })
	return out
}

func writeCommand(b *strings.Builder, cmd *cobra.Command) {
	fmt.Fprintf(b, "### %s\n\n", cmd.CommandPath())
	if short := strings.TrimSpace(cmd.Short); short != "" {
		b.WriteString(short + ".\n\n")
	}
	b.WriteString("```\n" + strings.TrimSpace(cmd.UseLine()) + "\n```\n\n")
	if aliases := cmd.Aliases; len(aliases) > 0 {
		b.WriteString("Aliases: " + strings.Join(aliases, ", ") + "\n\n")
	}
	if long := strings.TrimSpace(cmd.Long); long != "" && long != strings.TrimSpace(cmd.Short) {
		b.WriteString(long + "\n\n")
	}
	if flags := cmd.LocalNonPersistentFlags(); flags.HasAvailableFlags() {
		writeFlagTable(b, flags)
		b.WriteString("\n")
	}
	if example := firstExample(cmd.Example); example != "" {
		b.WriteString("Example:\n\n```\n" + example + "\n```\n\n")
	}
}

// firstExample returns the first example line of a command.
func firstExample(example string) string {
	for _, line := range strings.Split(example, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			return line
		}
	}
	return ""
}

// writeFlagTable renders a flag set as a markdown table, sorted by name,
// skipping hidden flags and --help.
func writeFlagTable(b *strings.Builder, flags *pflag.FlagSet) {
	var rows [][3]string
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		rows = append(rows, [3]string{flagName(f), flagDefault(f), escapeCell(f.Usage)})
	})
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i][0] < rows[j][0] })
	b.WriteString("| Flag | Default | Description |\n| --- | --- | --- |\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s | %s |\n", r[0], r[1], r[2])
	}
}

// flagName renders a flag as it appears in help: shorthand, long name,
// and value type for anything but a boolean.
func flagName(f *pflag.Flag) string {
	var b strings.Builder
	b.WriteString("`")
	if f.Shorthand != "" {
		b.WriteString("-" + f.Shorthand + ", ")
	}
	b.WriteString("--" + f.Name)
	if t := f.Value.Type(); t != "bool" {
		b.WriteString(" " + t)
	}
	b.WriteString("`")
	return b.String()
}

// flagDefault renders a flag default, or an empty cell when there is
// nothing useful to show.
func flagDefault(f *pflag.Flag) string {
	def := f.DefValue
	switch def {
	case "", "false", "0", "[]", "0s":
		return ""
	}
	return "`" + escapeCell(def) + "`"
}

// escapeCell makes a string safe inside a markdown table cell.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.ReplaceAll(s, "\n", " ")
}

// schemaSections are the payloads documented in full, in the order an
// agent meets them.
var schemaSections = []string{
	"node.context",
	"node.inspect",
	"file.tree",
	"tokens.export",
	"render",
	"assets.export",
}

// OutputSchemas renders the output contract: the success envelope, the
// error envelope, and the data payloads of the commands an agent uses
// most, from the same schema registry as figctl schema.
func OutputSchemas() string {
	entries := map[string]cli.SchemaEntry{}
	var names []string
	for _, e := range cli.SchemaEntries() {
		entries[e.Command] = e
		if e.Command != "envelope" {
			names = append(names, e.Command)
		}
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# figctl output schemas\n\n")
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("Every command prints one envelope. `data` is the command's own payload;\n")
	b.WriteString("the fields below are its shape. Run `figctl schema <command>` for the\n")
	b.WriteString("machine readable JSON Schema of any payload.\n\n")

	b.WriteString("## The success envelope\n\n")
	writeFields(&b, entries["envelope"])
	b.WriteString("\nRead `hints` on every call: they say what was degraded, truncated, or what\n")
	b.WriteString("to run next. `nextCursor` is non-null when more rows exist.\n\n")

	b.WriteString("## The error envelope\n\n")
	b.WriteString("Errors are printed on stdout in JSON mode with a non-zero exit code.\n")
	b.WriteString("Switch on `error.code` and follow `error.hint`.\n\n")
	writeFields(&b, cli.ErrorEnvelopeEntry())
	b.WriteString("\nExit codes: 0 success, 1 runtime or API error, 2 usage, 3 auth, 4 not found,\n")
	b.WriteString("5 rate limited, 6 partial success (the data is still on stdout, and the\n")
	b.WriteString("items that failed are in `data.failures`).\n\n")

	b.WriteString("## Data payloads\n\n")
	for _, name := range schemaSections {
		entry, ok := entries[name]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "### %s\n\n", name)
		if entry.Note != "" {
			b.WriteString(entry.Note + "\n\n")
		}
		writeFields(&b, entry)
		b.WriteString("\n")
	}

	b.WriteString("## Every payload with a schema\n\n")
	b.WriteString("`figctl schema <command>` prints the JSON Schema of any of these:\n\n")
	for _, name := range names {
		entry := entries[name]
		if entry.HasSchema {
			b.WriteString("- `" + name + "`\n")
		} else {
			b.WriteString("- `" + name + "` (no static schema: " + strings.TrimSuffix(entry.Note, ".") + ")\n")
		}
	}
	return b.String()
}

// writeFields renders the flattened field list of a schema.
func writeFields(b *strings.Builder, entry cli.SchemaEntry) {
	if !entry.HasSchema || len(entry.Fields) == 0 {
		b.WriteString("No static schema.\n")
		return
	}
	b.WriteString("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n")
	for _, f := range entry.Fields {
		required := ""
		if f.Required {
			required = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", f.Path, escapeCell(f.Type), required, escapeCell(f.Description))
	}
}
