package tokens

import (
	"fmt"
	"strings"
)

// DefaultModeSelector is the selector template used for every mode that
// is not the one in :root. The substring <mode> is replaced with the
// kebab cased mode name, so Dark becomes [data-theme="dark"].
const DefaultModeSelector = `[data-theme="<mode>"]`

// CSSOptions configures the CSS writer.
type CSSOptions struct {
	// ModeSelector is the selector template for a mode block; empty
	// means DefaultModeSelector.
	ModeSelector string
}

// CSS renders the document as custom properties: one :root block for the
// selected modes and one block per remaining mode.
//
// A property is named after the variable's WEB codeSyntax when it has
// one, because that field exists precisely to say what the variable is
// called in code; otherwise it is the kebab cased token path. Aliases
// become var(--target) in :root. Mode blocks inline their values, since
// the alias target of another mode is not part of the resolved document.
// Typography styles have no composite form in CSS, so they expand into
// one property per field (--heading-lg-font-size and so on), and layout
// grids expand into their column count, gutter, and margin.
//
// CSS expresses modes with selectors, so it always renders every mode
// whatever --mode-strategy asked for; the strategy only decides which
// mode fills :root.
func (d *Document) CSS(opts CSSOptions) ([]Output, error) {
	selector := opts.ModeSelector
	if selector == "" {
		selector = DefaultModeSelector
	}
	set := d.rootSet()
	var b strings.Builder
	fmt.Fprintf(&b, "/* %s */\n", d.header())
	out := Output{Name: "tokens.css", Tokens: len(set.Tokens)}

	seen := map[string]string{}
	b.WriteString("\n:root {\n")
	for _, t := range set.Tokens {
		for _, decl := range declarations(t) {
			if prev, exists := seen[decl.name]; exists {
				if prev != decl.value {
					out.Warnings = append(out.Warnings, fmt.Sprintf("custom property --%s is set by more than one token with different values; kept %s and dropped %s from %q", decl.name, prev, decl.value, t.Source))
				}
				continue
			}
			seen[decl.name] = decl.value
			fmt.Fprintf(&b, "  --%s: %s;\n", decl.name, decl.value)
		}
	}
	b.WriteString("}\n")

	for _, mode := range d.modeBlocks() {
		var block strings.Builder
		for _, t := range set.Tokens {
			value, ok := t.Modes[mode]
			if !ok || t.Mode == mode {
				continue
			}
			css := cssText(t.Type, value)
			if css == "" || seen[t.CSSName] == css {
				continue
			}
			fmt.Fprintf(&block, "  --%s: %s;\n", t.CSSName, css)
		}
		if block.Len() == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n%s {\n%s}\n", strings.ReplaceAll(selector, "<mode>", kebab(mode)), block.String())
	}
	out.Content = []byte(b.String())
	return []Output{out}, nil
}

// declaration is one CSS custom property.
type declaration struct {
	name  string
	value string
}

// declarations expands a token into the properties it contributes.
func declarations(t Token) []declaration {
	if len(t.Parts) > 0 {
		out := make([]declaration, 0, len(t.Parts))
		for _, p := range t.Parts {
			out = append(out, declaration{name: t.CSSName + "-" + p.Suffix, value: p.Value})
		}
		return out
	}
	value := t.CSS
	if t.Ref != "" {
		value = "var(--" + t.RefCSSName + ")"
	}
	if value == "" {
		return nil
	}
	return []declaration{{name: t.CSSName, value: value}}
}

// rootSet is the set that fills :root: the single set of the default and
// select strategies, or the first per mode set.
func (d *Document) rootSet() Set {
	for _, set := range d.Sets {
		if set.Mode == "" {
			return set
		}
	}
	if len(d.Sets) > 0 {
		return d.Sets[0]
	}
	return Set{}
}

func (d *Document) header() string {
	name := d.File
	if name == "" {
		name = "a Figma file"
	}
	if d.Version != "" {
		name += " (version " + d.Version + ")"
	}
	return "Design tokens from " + name + ", generated by figctl. Do not edit by hand."
}
